[package]
name = "ditto"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[features]
default = ["socket_tokio_tcp"]
socket_tokio_tcp = ["tokio", "tokio-util"]

[dependencies]
futures = "0.3"
tokio = { version = "0.3", features = ["full"], optional = true }
tokio-util = { version = "0.5", features = ["compat"], optional = true }
