[package]
name = "ditto"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[features]
default = ["async_runtime_tokio", "socket_tokio_tcp", "serialize_capnp", "crypto_signature_ring_ed25519"]
socket_tokio_tcp = ["tokio", "tokio-util"]
serialize_capnp = ["capnpc", "capnp", "capnp-futures"]
async_runtime_tokio = ["tokio"]
crypto_signature_ring_ed25519 = ["ring"]
expose_impl = []

[build-dependencies]
itertools = "0.9"
capnpc = { version = "0.13", optional = true }

[dependencies]
futures = "0.3"
once_cell = "1.5"
tokio = { version = "0.3", features = ["full"], optional = true }
tokio-util = { version = "0.5", features = ["compat"], optional = true }
capnp = { version = "0.13", optional = true }
capnp-futures = { version = "0.13", optional = true }
ring = { version = "0.16", optional = true }
