[package]
name = "ditto"
version = "0.1.0"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"

[features]
# choose one of each prefixes: async, threadpool, socket, serialize, crypto_signature
# this decopulation of the abstraction from the backend allows experimenting with
# different libraries, to probe which one has better performance for our use case
default = [
    "async_runtime_tokio",
    "threadpool_crossbeam",
    "socket_tokio_tcp",
    "serialize_capnp",
    "crypto_signature_ring_ed25519"
]
socket_tokio_tcp = ["tokio", "tokio-util"]
serialize_capnp = ["capnpc", "capnp", "capnp-futures"]
async_runtime_tokio = ["tokio"]
crypto_signature_ring_ed25519 = ["ring"]
threadpool_crossbeam = ["threadpool-crossbeam-channel"]
expose_impl = []

[build-dependencies]
itertools = "0.9"
capnpc = { version = "0.13", optional = true }

[dependencies]
futures = "0.3"
once_cell = "1.5"
tokio = { version = "0.3", features = ["full"], optional = true }
tokio-util = { version = "0.5", features = ["compat"], optional = true }
capnp = { version = "0.13", optional = true }
capnp-futures = { version = "0.13", optional = true }
ring = { version = "0.16", optional = true }
threadpool-crossbeam-channel = { version = "1.8", optional = true }
