[package]
name = "febft"
version = "0.1.0"
description = "A BFT SMR library in Rust!"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/febft/febft"
repository = "https://github.com/febft/febft"
documentation = "https://docs.rs/febft"
readme = "README.md"

[features]
# Consult the crate documentation for more details on the features.
default = [
    "async_runtime_tokio",
    "threadpool_crossbeam",
    "socket_tokio_tcp",
    "serialize_serde",
    "channel_futures_mpsc",
    "crypto_signature_ring_ed25519",
    "crypto_hash_blake3_blake3"
]

socket_tokio_tcp = ["tokio", "tokio-util"]
socket_async_std_tcp = ["async-std"]
socket_rio_tcp = ["rio", "socket2"]

serialize_serde = ["serde"]

async_runtime_tokio = ["tokio"]
async_runtime_async_std = ["async-std"]

crypto_signature_ring_ed25519 = ["ring"]
crypto_hash_ring_sha2 = ["ring"]
crypto_hash_blake3_blake3 = ["blake3"]

threadpool_crossbeam = ["threadpool-crossbeam-channel"]
threadpool_cthpool = ["cthpool"]

channel_futures_mpsc = []
channel_flume_mpmc = ["flume"]
channel_async_channel_mpmc = ["async-channel"]

#bench = ["expose_impl", "oneshot", "futures-timer", "async-semaphore"]
expose_impl = []

[build-dependencies]
itertools = "0.9"

[dev-dependencies]
bincode = "1"
rand_core = { version = "0.6", features = ["getrandom"] }

[dependencies]
oneshot = "0.1"
futures = "0.3"
futures-timer = "3"
async-tls = "0.11"
rustls = "0.19"
smallvec = { version = "1", features = ["union", "write"] }
async-std = { version = "1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
tokio-util = { version = "0.6", features = ["compat"], optional = true }
ring = { version = "0.16", optional = true }
threadpool-crossbeam-channel = { version = "1", optional = true }
#async-semaphore = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
cthpool = { git = "https://github.com/sug0/cthpool", optional = true }
rio = { version = "0.9", optional = true }
socket2 = { version = "0.4", optional = true }
blake3 = { version = "0.3", optional = true }
flume = { version = "0.10", optional = true }
async-channel = { version = "1", optional = true }
