[package]
name = "febft"
version = "0.1.0"
description = "A BFT SMR library in Rust!"
authors = ["Tiago Carvalho <up201605259@fc.up.pt>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/febft/febft"
repository = "https://github.com/febft/febft"
documentation = "https://docs.rs/febft"
readme = "README.md"

[features]
# Consult the crate documentation for more details on the features.
default = [
    "async_runtime_tokio",
    "threadpool_crossbeam",
    "socket_tokio_tcp",
    "serialize_serde_bincode",
    "crypto_signature_ring_ed25519",
    "crypto_hash_ring_sha2"
]

socket_tokio_tcp = ["tokio", "tokio-util"]
socket_async_std_tcp = ["async-std"]
socket_rio_tcp = ["rio", "socket2"]

serialize_capnp = ["capnp"]
serialize_serde = ["serde"]
serialize_serde_cbor = ["serialize_serde", "serde_cbor"]
serialize_serde_bincode = ["serialize_serde", "bincode"]
serialize_serde_messagepack = ["serialize_serde", "rmp-serde"]

async_runtime_tokio = ["tokio"]
async_runtime_async_std = ["async-std"]

crypto_signature_ring_ed25519 = ["ring"]
crypto_hash_ring_sha2 = ["ring"]

threadpool_crossbeam = ["threadpool-crossbeam-channel"]
threadpool_cthpool = ["cthpool"]

#bench = ["expose_impl", "oneshot", "futures-timer", "async-semaphore"]
expose_impl = []

[build-dependencies]
itertools = "0.9"
capnpc = "0.14"

[dev-dependencies]
rcgen = "0.8"
rand_core = { version = "0.6", features = ["getrandom"] }

[dependencies]
futures = "0.3"
futures-timer = "3"
async-tls = "0.11"
rustls = "0.19"
smallvec = { version = "1", features = ["union", "write"] }
async-std = { version = "1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
tokio-util = { version = "0.6", features = ["compat"], optional = true }
capnp = { version = "0.14", optional = true }
ring = { version = "0.16", optional = true }
threadpool-crossbeam-channel = { version = "1", optional = true }
#oneshot = { version = "0.1", optional = true }
#async-semaphore = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
bincode = { version = "1", optional = true }
cthpool = { git = "https://github.com/sug0/cthpool", optional = true }
rmp-serde = { version = "0.15", optional = true }
serde_cbor = { version = "0.11", optional = true }
rio = { version = "0.9", optional = true }
socket2 = { version = "0.4", optional = true }
