[package]
name = "febft-state-transfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

serialize-serde = ["serde"]
serialize-capnp = ["febft-capnp", "capnp"]

[dependencies]

serde = { version = "1.0.159", optional = true }
capnp = { version = "0.16.1", optional = true }

febft-capnp = { path = "../febft-capnp", optional = true }
febft-execution = { path = "../febft-execution" }
febft-common = { path = "../febft-common" }
febft-communication = { path = "../febft-communication" }
febft-messages = { path = "../febft-messages" }